-- SELECT MAX(num_seats)
-- FROM tables
-- 
-- SELECT MAX(amount_billed) as max_billed, MAX(amount_tipped) AS max_tipped
-- FROM bookings
-- 
-- SELECT MIN(booking_date), MAX(booking_date) FROM bookings;
-- 
-- SELECT MIN(category), MAX(category) FROM tables;